ALTER TABLE "Product"
ADD COLUMN "ycLengthCm" DOUBLE PRECISION,
ADD COLUMN "ycWidthCm" DOUBLE PRECISION,
ADD COLUMN "ycHeightCm" DOUBLE PRECISION,
ADD COLUMN "ycVolumeM3" DOUBLE PRECISION,
ADD COLUMN "ycSpecsSyncedAt" TIMESTAMP(3);
